# https://docs.netlify.com/configure-builds/file-based-configuration/#configuration-details

[build]
command = "npm run build"
publish = "build"

[[rewrite]]
from = "/*"
to = "/index.html"
status = 200
